/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pl_asndktest_jni_NdkTest */
#include "stdio.h"

#include "libavcodec/avcodec.h"  
#include "libavformat/avformat.h"  
#include "libavfilter/avfilter.h"  

#ifndef _Included_com_pl_asndktest_jni_NdkTest
#define _Included_com_pl_asndktest_jni_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pl_asndktest_jni_NdkTest
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pl_asndktest_jni_NdkTest_getStringFromJni
  (JNIEnv * env, jobject thiz)
{
    char info[10000] = { 0 };
    sprintf(info, "%s\n", avcodec_configuration());
    return (*env)->NewStringUTF(env, info);
    //return (*env)->NewStringUTF(env, "HelloWorld from JNI !");
}

JNIEXPORT jstring JNICALL Java_com_pl_asndktest_jni_NdkTest_avformatinfo
  (JNIEnv * env, jobject thiz)
{
    char info[40000] = { 0 };  
  
    av_register_all();  
  
    AVInputFormat *if_temp = av_iformat_next(NULL);  
    AVOutputFormat *of_temp = av_oformat_next(NULL);  
    //Input  
    while(if_temp!=NULL){  
        sprintf(info, "%s[In ][%10s]\n", info, if_temp->name);  
        if_temp=if_temp->next;  
    }  
    //Output  
    while (of_temp != NULL){  
        sprintf(info, "%s[Out][%10s]\n", info, of_temp->name);  
        of_temp = of_temp->next;  
    }  
    //LOGE("%s", info);  
    return (*env)->NewStringUTF(env, info); 
}

JNIEXPORT jstring JNICALL Java_com_pl_asndktest_jni_NdkTest_avcodecinfo
  (JNIEnv * env, jobject thiz)
{
    char info[40000] = { 0 };  
  
    av_register_all();  
  
    AVCodec *c_temp = av_codec_next(NULL);  
  
    while(c_temp!=NULL){  
        if (c_temp->decode!=NULL){  
            sprintf(info, "%s[Dec]", info);  
        }  
        else{  
            sprintf(info, "%s[Enc]", info);  
        }  
        switch (c_temp->type){  
        case AVMEDIA_TYPE_VIDEO:  
            sprintf(info, "%s[Video]", info);  
            break;  
        case AVMEDIA_TYPE_AUDIO:  
            sprintf(info, "%s[Audio]", info);  
            break;  
        default:  
            sprintf(info, "%s[Other]", info);  
            break;  
        }  
        sprintf(info, "%s[%10s]\n", info, c_temp->name);  
  
          
        c_temp=c_temp->next;  
    }  
    //LOGE("%s", info);  
  
    return (*env)->NewStringUTF(env, info); 
}

#ifdef __cplusplus
}
#endif
#endif
